### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by NayeliMoraless** [SistemasTecTlaxiaco/actividad-1-infografia-NayeliMoraless#1]
[Infografia.pdf](https://github.com/user-attachments/files/16791817/Infografia.pdf)

**Comment by ArcangelGC** [comment]
Recibo de enterado, incluye todo en base a la rubrica solo faltaron dos ídeas por eso la calificación baja.
Calif. 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
